name: python_class
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numpy=2.3.4=py314hde9b8b7_1
  - numpy-base=2.3.4=py314hb4b2851_1
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyh0d26453_1
  - python=3.14.0=h1858270_101_cp314
  - python_abi=3.14=1_cp314
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/anaconda3/envs/python_class
